# Configure-option regression tests without compiling dependencies.
if(NOT DEFINED SPIN_OPTION_CASE)
    foreach(case none silent vole logvole foleage ringlpn bitpolymul off source nofetch explicitfetch)
        execute_process(COMMAND "${CMAKE_COMMAND}" "-DSPIN_OPTION_CASE=${case}"
            -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result
            OUTPUT_VARIABLE output ERROR_VARIABLE errors)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "SPIN option case ${case} failed:\n${output}\n${errors}")
        endif()
    endforeach()
    message(STATUS "SPIN option defaults and fetch overrides passed")
    return()
endif()
cmake_minimum_required(VERSION 3.20)
set(ENABLE_LOGVOLE OFF)
set(FETCH_AUTO ON)
set(expected ON)
set(expected_fetch ON)
if(SPIN_OPTION_CASE STREQUAL none)
    set(expected OFF)
    set(expected_fetch OFF)
elseif(SPIN_OPTION_CASE STREQUAL silent)
    set(ENABLE_SILENTOT ON)
elseif(SPIN_OPTION_CASE STREQUAL vole)
    set(ENABLE_SILENT_VOLE ON)
elseif(SPIN_OPTION_CASE STREQUAL logvole)
    set(ENABLE_LOGVOLE ON)
elseif(SPIN_OPTION_CASE STREQUAL foleage)
    set(ENABLE_FOLEAGE ON)
elseif(SPIN_OPTION_CASE STREQUAL ringlpn)
    set(ENABLE_RINGLPN ON)
elseif(SPIN_OPTION_CASE STREQUAL bitpolymul)
    set(ENABLE_BITPOLYMUL ON)
else()
    set(ENABLE_SILENTOT ON)
    if(SPIN_OPTION_CASE STREQUAL off)
        set(ENABLE_SPIN OFF)
        set(expected OFF)
        set(expected_fetch OFF)
    elseif(SPIN_OPTION_CASE STREQUAL source)
        set(LIBOTE_SPIN_SOURCE /source/override)
        set(expected_fetch OFF)
    elseif(SPIN_OPTION_CASE STREQUAL nofetch)
        set(FETCH_SPIN OFF)
        set(expected_fetch OFF)
    elseif(SPIN_OPTION_CASE STREQUAL explicitfetch)
        set(FETCH_AUTO OFF)
        set(FETCH_SPIN ON)
    endif()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/buildOptions.cmake")
if(NOT "${ENABLE_SPIN}" STREQUAL "${expected}" OR NOT "${FETCH_SPIN_IMPL}" STREQUAL "${expected_fetch}")
    message(FATAL_ERROR "Unexpected ENABLE_SPIN=${ENABLE_SPIN}, FETCH_SPIN_IMPL=${FETCH_SPIN_IMPL}")
endif()
