#pragma once

#define LIBOTE_VERSION_MAJOR 1
#define LIBOTE_VERSION_MINOR 0
#define LIBOTE_VERSION_PATCH 1

#define LIBOTE_VERSION (LIBOTE_VERSION_MAJOR * 10000 + LIBOTE_VERSION_MINOR * 100 + LIBOTE_VERSION_PATCH)
