#ifndef OT_CONFIG_H
#define OT_CONFIG_H

//#define NOTS 16
//#define HASHBYTES 32
//#define HASHBITS (HASHBYTES * 8)
//#define PACKBYTES 32


//#define SIMPLEST_OT_NOTS 16 
#define SIMPLEST_OT_HASHBYTES 32 
#define SIMPLEST_OT_HASHBITS (SIMPLEST_OT_HASHBYTES * 8) 
#define SIMPLEST_OT_PACK_BYTES 32 
#define SIMPLEST_OT_DIS_T 1 
#define SIMPLEST_OT_VERBOSE 1 

#endif //ifndef OT_CONFIG_H

