
include("${CMAKE_CURRENT_LIST_DIR}/libOTeFindBuildDir.cmake")

LOAD_CACHE("${libOTe_BIN_DIR}/" INCLUDE_INTERNALS 
    ENABLE_BOOST 
    ENABLE_RELIC
    ENABLE_SIMPLESTOT_ASM
    ENABLE_MR_KYBER
    )

